patterns:
  require:
    - regex: ($CI_MERGE_REQUEST_PROJECT_URL/(-/)?(issues|merge_requests)/[0-9]+|https://bugzilla.gnome.org/show_bug.cgi?id=[0-9]+)
      message: Commit message must contain a link to an issue or merge request
